# Generated by Django 3.2.7 on 2021-11-10 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20211108_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('last_logout', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'working LoginLog',
                'verbose_name_plural': 'working LoginLogs',
                'db_table': 'login_log',
            },
        ),
    ]
