# Generated by Django 3.2.7 on 2021-12-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20211111_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'ADMIN'), ('2', 'Staff'), ('3', 'Worker')], default='3', max_length=10),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='work_place',
            field=models.CharField(choices=[('remote', 'Praca Zdalna'), ('office', 'Biuro'), ('day_off', 'Weekend'), ('vacation', 'Urlop'), ('holiday', 'Święto'), ('seak_leave', 'Zwolnienie lekarskie')], default='office', max_length=255),
        ),
    ]
