# Generated by Django 3.2.7 on 2022-01-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20211223_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('currently', 'Currently Working'), ('fired', 'Fired')], default='empty', max_length=100),
        ),
    ]
